# Generated by Django 4.2.11 on 2024-03-12 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_birth_date_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_login_date',
        ),
    ]
