# Generated by Django 4.2.11 on 2024-03-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userspostrequest_created_on_userspostrequest_excerpt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userspostrequest',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
