# Generated by Django 4.2.11 on 2024-03-04 12:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_alter_post_like_count_alter_post_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sillied',
            field=models.ManyToManyField(blank=True, default=None, related_name='silly_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='silly_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
