# Generated by Django 4.2.11 on 2024-03-04 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_post_sillied_post_silly_count_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='more',
            field=models.ManyToManyField(related_name='more_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='more_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
