# Generated by Django 4.2.11 on 2024-03-04 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_uservote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserVote',
        ),
    ]
