# Generated by Django 4.2.11 on 2024-03-12 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0015_alter_post_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='more',
            field=models.ManyToManyField(blank=True, related_name='more_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
