# Generated by Django 4.2.10 on 2024-02-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='Home',
        ),
        migrations.RenameField(
            model_name='collaboraterequest',
            old_name='read',
            new_name='posted',
        ),
        migrations.AddField(
            model_name='collaboraterequest',
            name='title',
            field=models.CharField(default='Default Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='collaboraterequest',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
