# Generated by Django 4.2.11 on 2024-03-09 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_about_home_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
